"""Generate src/web_page.h from src/index.html before the build.

The Wi-Fi configuration page is kept as plain HTML so it stays easy to edit;
at build time it is turned into a C string header. The file is only rewritten
when its content actually changes, so incrementing builds stay incremental.
"""
import os

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")
SOURCE = os.path.join(PROJECT_DIR, "src", "index.html")
TARGET = os.path.join(PROJECT_DIR, "src", "web_page.h")

HEADER = "/* Auto generated from src/index.html by tools/gen_web_page.py. */\n"
HEADER += "/* Do not edit this file by hand, edit src/index.html instead. */\n"
HEADER += "#pragma once\n\n"


def build_header():
    with open(SOURCE, "rb") as handle:
        html = handle.read().decode("utf-8")

    escaped = (
        html.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "")
        .replace("\n", '\\n"\n"')
    )

    content = HEADER
    content += "static const char WEB_PAGE_HTML[] =\n"
    content += '"' + escaped + '";\n\n'
    content += "#define WEB_PAGE_HTML_LEN (sizeof(WEB_PAGE_HTML) - 1)\n"

    if os.path.isfile(TARGET):
        with open(TARGET, "r") as handle:
            if handle.read() == content:
                return

    with open(TARGET, "w") as handle:
        handle.write(content)


build_header()
