idf_component_register(
    SRCS
        "main.c"
        "motion_core.c"
        "app_state.c"
        "motor_driver.c"
        "lcd_font.c"
        "display.c"
        "self_test.c"
        "wifi_provision.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_lcd
        esp_driver_gpio
        esp_driver_spi
        esp_timer
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_http_server
        lwip
)
